name: Fortify AST Scan
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '18 17 * * 6'
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Create Placeholder
        run: |
          mkdir -p artifacts
          echo "Placeholder for upload-artifact" > artifacts/placeholder.txt

      - name: Setup Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: placeholder-artifact
          path: artifacts/placeholder.txt

      - name: Verify Secret Presence
        run: |
          if [ -n "$FOD_USER" ]; then
            echo "FOD_USER is set"
          else
            echo "FOD_USER is not set"
          fi
        env:
          FOD_USER: ${{ secrets.FOD_USER }}

      - name: Run Fortify SAST Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          FOD_URL: "https://ams.fortify.com"
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE: "${{ github.repository }}:${{ github.ref_name }}"
